### ISSUE TITLE
PicoDet用coco训练集train报错

### ISSUE THREAD

**Issue by Pillar1989** [ppogg/YOLOv5-Lite#101]
如图

**Comment by Pillar1989** [comment]
https://github.com/ppogg/YOLOv5-Lite/issues/85#issuecomment-1011824435

**Comment by ppogg** [comment]
已接收此bug！近期给予反馈！

**Comment by ppogg** [comment]
已修复此bug！

**Comment by Pillar1989** [comment]
感谢你进一步的修复，已经取得了很大的进展，但是还是有问题，看起来是网络结构的问题。 @ppogg 
```bash
(base) se@stu:~/YOLOv5-Lite$ python train.py --img 320 --batch 6000 --epochs 200 --data coco.yaml --cfg PicoDet-s.yaml
github: up to date with https://github.com/ppogg/YOLOv5-Lite/ ✅
YOLOv5 🚀 v1.3-108-ge1e9e98 torch 1.10.1 CUDA:0 (NVIDIA A100-PCIE-40GB, 40536.1875MB)

Namespace(weights='weights/v5lite-s.pt', cfg='./models/hub/PicoDet-s.yaml', data='./data/coco.yaml', hyp='data/hyp.scratch.yaml', epochs=200, batch_size=6000, img_size=[320, 320], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, image_weights=False, device='0', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, workers=8, project='runs/train', entity=None, name='exp', exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias='latest', world_size=1, global_rank=-1, save_dir='runs/train/exp8', total_batch_size=6000)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.001, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.2, mixup=0.0
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id 3dkjqf9j.
2022-01-15 01:53:29.272839: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/se/anaconda3/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-15 01:53:29.272879: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

                 from  n    params  module                                  arguments                     
  0                -1  1       928  models.common.CBH                       [3, 32, 3, 2]                 
  1                -1  1     23296  models.common.ES_Bottleneck             [32, 96, 2]                   
  2                -1  2     44160  models.common.ES_Bottleneck             [96, 96, 1]                   
  3                -1  1     93792  models.common.ES_Bottleneck             [96, 192, 2]                  
  4                -1  5    416640  models.common.ES_Bottleneck             [192, 192, 1]                 
  5                -1  1    362688  models.common.ES_Bottleneck             [192, 384, 2]                 
  6                -1  2    646656  models.common.ES_Bottleneck             [384, 384, 1]                 
  7                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
  8           [-1, 6]  1         0  models.common.Concat                    [1]                           
  9                -1  1     90528  models.common.BottleneckCSP             [576, 96, 1, False]           
 10                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 4]  1         0  models.common.Concat                    [1]                           
 13                -1  1     62880  models.common.BottleneckCSP             [288, 96, 1, False]           
 14                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 2]  1         0  models.common.Concat                    [1]                           
 17                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 18                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 21                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 24           [-1, 7]  1         0  models.common.ADD                       [1]                           
 25                -1  1     17904  models.common.DWConvblock               [144, 96, 5, 2]               
 26  [17, 20, 23, 25]  1    131920  models.yolo.Detect                      [80, [[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]], [96, 96, 96, 96]]
Traceback (most recent call last):
  File "/home/se/YOLOv5-Lite/train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/se/YOLOv5-Lite/train.py", line 89, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 93, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "/home/se/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/se/YOLOv5-Lite/models/common.py", line 678, in forward
    return torch.add(x1, x2, alpha=self.a)
RuntimeError: The size of tensor a (96) must match the size of tensor b (192) at non-singleton dimension 1

wandb: Waiting for W&B process to finish, PID 3696320... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/se/YOLOv5-Lite/wandb/offline-run-20220115_015328-3dkjqf9j
wandb: Find logs at: ./wandb/offline-run-20220115_015328-3dkjqf9j/logs/debug.log
wandb: 
```

**Comment by ppogg** [comment]
已收到，我观察到你的模型和我们repo的不一样
```
#  CSP-PAN
head:
  [ [ -1, 1, Conv, [ 384, 1, 1 ] ], # 7
    [ [ -1, 6 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 9 (P3/8-small)

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 10
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 13

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 14
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 17 (P3/8-small)

    [-1, 1, DWConvblock, [ 192, 5, 2 ]], # 18
    [ [ -1, 14 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 20 (P4/16-medium)

    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],
    [ [ -1, 10 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 23 (P5/32-large)

    [ [ -1, 7 ], 1, ADD, [ 1 ] ],  # cat head P6
    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],  # 26 (P5/32-large)

    [ [ 17, 20, 23, 25 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5, P6)
  ]
```

**Comment by Pillar1989** [comment]
是一样的，应该是解析出来不一样。 @ppogg 
```bash
(base) se@stu:~/YOLOv5-Lite$ cat models/hub/PicoDet-s.yaml
# parameters
nc: 80  # number of classes
depth_multiple: 0.75  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors: 4 # auto-anchor 4 anchors per P output layer

# custom backbone
backbone:
  # [from, number, module, args]
  [ [ -1, 1, CBH, [ 64, 3, 2 ] ],    # 0-P2/4
    [ -1, 1, ES_Bottleneck, [ 192, 2 ] ], # 1-P3/8
    [ -1, 3, ES_Bottleneck, [ 192, 1 ] ], # 2
    [ -1, 1, ES_Bottleneck, [ 384, 2 ] ], # 3-P5/16
    [ -1, 7, ES_Bottleneck, [ 384, 1 ] ], # 4
    [ -1, 1, ES_Bottleneck, [ 768, 2 ] ], # 5-P7/32
    [ -1, 3, ES_Bottleneck, [ 768, 1 ] ], # 6
  ]

#  CSP-PAN
head:
  [ [ -1, 1, Conv, [ 384, 1, 1 ] ], # 7
    [ [ -1, 6 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 9 (P3/8-small)

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 10
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 13

    [ -1, 1, Conv, [ 192, 1, 1 ] ], # 14
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 17 (P3/8-small)

    [-1, 1, DWConvblock, [ 192, 5, 2 ]], # 18
    [ [ -1, 14 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 20 (P4/16-medium)

    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],
    [ [ -1, 10 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 1, BottleneckCSP, [ 192, False ] ],  # 23 (P5/32-large)

    [ [ -1, 7 ], 1, ADD, [ 1 ] ],  # cat head P6
    [ -1, 1, DWConvblock, [ 192, 5, 2 ] ],  # 26 (P5/32-large)

    [ [ 17, 20, 23, 25 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5, P6)
  ]
(base) se@stu:~/YOLOv5-Lite$ python train.py --img 320 --batch 6000 --epochs 200 --data coco.yaml --cfg PicoDet-s.yaml
github: up to date with https://github.com/ppogg/YOLOv5-Lite/ ✅
YOLOv5 🚀 v1.3-108-ge1e9e98 torch 1.10.1 CUDA:0 (NVIDIA A100-PCIE-40GB, 40536.1875MB)

Namespace(weights='weights/v5lite-s.pt', cfg='./models/hub/PicoDet-s.yaml', data='./data/coco.yaml', hyp='data/hyp.scratch.yaml', epochs=200, batch_size=6000, img_size=[320, 320], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, image_weights=False, device='0', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, workers=8, project='runs/train', entity=None, name='exp', exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias='latest', world_size=1, global_rank=-1, save_dir='runs/train/exp16', total_batch_size=6000)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.001, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.2, mixup=0.0
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id ydt5op58.
2022-01-15 10:15:58.920679: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/se/anaconda3/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-15 10:15:58.920719: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

                 from  n    params  module                                  arguments                     
  0                -1  1       928  models.common.CBH                       [3, 32, 3, 2]                 
  1                -1  1     23296  models.common.ES_Bottleneck             [32, 96, 2]                   
  2                -1  2     44160  models.common.ES_Bottleneck             [96, 96, 1]                   
  3                -1  1     93792  models.common.ES_Bottleneck             [96, 192, 2]                  
  4                -1  5    416640  models.common.ES_Bottleneck             [192, 192, 1]                 
  5                -1  1    362688  models.common.ES_Bottleneck             [192, 384, 2]                 
  6                -1  2    646656  models.common.ES_Bottleneck             [384, 384, 1]                 
  7                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
  8           [-1, 6]  1         0  models.common.Concat                    [1]                           
  9                -1  1     90528  models.common.BottleneckCSP             [576, 96, 1, False]           
 10                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 4]  1         0  models.common.Concat                    [1]                           
 13                -1  1     62880  models.common.BottleneckCSP             [288, 96, 1, False]           
 14                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 2]  1         0  models.common.Concat                    [1]                           
 17                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 18                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 21                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 24           [-1, 7]  1         0  models.common.ADD                       [1]                           
 25                -1  1     17904  models.common.DWConvblock               [144, 96, 5, 2]               
 26  [17, 20, 23, 25]  1    131920  models.yolo.Detect                      [80, [[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]], [96, 96, 96, 96]]
Traceback (most recent call last):
  File "/home/se/YOLOv5-Lite/train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/se/YOLOv5-Lite/train.py", line 89, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 93, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "/home/se/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/se/YOLOv5-Lite/models/common.py", line 678, in forward
    return torch.add(x1, x2, alpha=self.a)
RuntimeError: The size of tensor a (96) must match the size of tensor b (192) at non-singleton dimension 1

wandb: Waiting for W&B process to finish, PID 3709702... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/se/YOLOv5-Lite/wandb/offline-run-20220115_101557-ydt5op58
wandb: Find logs at: ./wandb/offline-run-20220115_101557-ydt5op58/logs/debug.log
wandb: 
(base) se@stu:~/YOLOv5-Lite$ 
```

**Comment by Pillar1989** [comment]
代码是跟GitHub上是一致的，没有改
```
(base) se@stu:~/YOLOv5-Lite$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   data/coco.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore
	data/coco1.yaml

no changes added to commit (use "git add" and/or "git commit -a")
(base) se@stu:~/YOLOv5-Lite$ git remote -v
origin	https://github.com/ppogg/YOLOv5-Lite/ (fetch)
origin	https://github.com/ppogg/YOLOv5-Lite/ (push)
(base) se@stu:~/YOLOv5-Lite$ git pull
Already up to date.
(base) se@stu:~/YOLOv5-Lite$ 
```

**Comment by ppogg** [comment]
已修复，再试试~

**Comment by Pillar1989** [comment]
可以了，谢谢了，虽然有其他的问题，我们另外的issues再讨论

**Comment by ppogg** [comment]
好的，不客气，有问题欢迎再交流~

**Comment by machine52vision** [comment]
最新代码，怎么还有一样的问题，没有修复吗？

**Comment by ppogg** [comment]
您好，这是刚下载的最新的YOLOv5-Lite，代码不做任何更改，稳稳训练的情况，模型为PicoDet-s
![1645332809(1)](https://user-images.githubusercontent.com/82716366/154828919-00345e39-4bfc-48f4-b456-563ff1b3c75a.png)

**Comment by machine52vision** [comment]
我也是最新master，和你之前问题一样，维度不一致



| |
machine52vision
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月20日 12:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ppogg/YOLOv5-Lite] PicoDet用coco训练集train报错 (Issue #101) |

您好，这是刚下载的最新的YOLOv5-Lite，代码不做任何更改，稳稳训练的情况，模型为PicoDet-s


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ppogg** [comment]
是否修改过代码？

**Comment by machine52vision** [comment]
原版未修改



| |
machine52vision
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月20日 22:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ppogg/YOLOv5-Lite] PicoDet用coco训练集train报错 (Issue #101) |

是否修改过代码？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pillar1989** [comment]
@machine52vision  最新的代码，确实是可以训练的，检查你那边的环境。如果训练完了，希望能贡献评估的结果。

**Comment by Pillar1989** [comment]
昨天顺手训练完了，结果给大家瞅瞅
```bash
100 epochs completed in 6.174 hours.

Fusing layers... 
/home/se/anaconda3/lib/python3.9/site-packages/thop/vision/basic_hooks.py:92: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  kernel = torch.DoubleTensor([*(x[0].shape[2:])]) // torch.DoubleTensor(list((m.output_size,))).squeeze()
Model Summary: 627 layers, 892000 parameters, 0 gradients, 8.5 GFLOPS
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:17<00:00,  2.17s/it]
                 all        5000       10777       0.658       0.443       0.508       0.273

Evaluating pycocotools mAP... saving runs/train/exp40/_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '../coco/annotations/instances_val2017.json'
Fusing layers... 
Model Summary: 627 layers, 892000 parameters, 0 gradients, 8.5 GFLOPS
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.90s/it]
                 all        5000       10777       0.658       0.443       0.508       0.273

Evaluating pycocotools mAP... saving runs/train/exp40/_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '../coco/annotations/instances_val2017.json'
Optimizer stripped from runs/train/exp40/weights/last.pt, 2.3MB
Optimizer stripped from runs/train/exp40/weights/best.pt, 2.3MB
Images sizes do not match. This will causes images to be display incorrectly in the UI.

wandb: Waiting for W&B process to finish, PID 3488655... (success).
wandb: Run history:
wandb:        metrics/mAP_0.5 ▁▁▃▄▅▅▆▆▇▇▇▇▇▇▇█████████████████████████
wandb:   metrics/mAP_0.5:0.95 ▁▁▂▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇▇▇▇███████████████████
wandb:      metrics/precision ▁▂▃▄▅▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇███████████▇▇▇
wandb:         metrics/recall ▁▁▄▅▆▆▆▆▇▇▇▇▇▇▇▇█████████████▇▇█████████
wandb:         train/box_loss █▆▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         train/cls_loss █▃▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         train/obj_loss ▄█▆▅▄▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/box_loss █▆▄▃▃▃▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/cls_loss █▅▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/obj_loss ▅█▆▅▄▄▃▃▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  x/lr0 ▂███████▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▄▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr1 ▂███████▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▄▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr2 █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:        metrics/mAP_0.5 0.53117
wandb:   metrics/mAP_0.5:0.95 0.28308
wandb:      metrics/precision 0.66123
wandb:         metrics/recall 0.46708
wandb:         train/box_loss 0.04517
wandb:         train/cls_loss 0.00016
wandb:         train/obj_loss 0.00334
wandb:           val/box_loss 0.04486
wandb:           val/cls_loss 0.00025
wandb:           val/obj_loss 0.00337
wandb:                  x/lr0 0.0002
wandb:                  x/lr1 0.0002
wandb:                  x/lr2 0.0002
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/se/YOLO/YOLOv5-Lite/wandb/offline-run-20220221_012242-2q6nft5e
wandb: Find logs at: ./wandb/offline-run-20220221_012242-2q6nft5e/logs/debug.log
wandb: 

```

**Comment by dengxiongshi** [comment]
这是我训练PicoDet的命令：
train.py --weights weights/v5lite-s.pt --cfg models/hub/PicoDet-s.yaml --data datasets/coco128/coco.yaml --batch-size 4 --img-size 320 --name picodet
曲线如下：
![image](https://github.com/ppogg/YOLOv5-Lite/assets/31054848/3c7ef75f-ffae-451e-8798-5669c14effd8)
谁能讲解下为什么会这样

**Comment by dengxiongshi** [comment]
这是我训练yolov5_lites的命令：
train.py --weights weights/v5lite-s.pt --cfg models/v5Lite-s.yaml --data datasets/coco128/coco.yaml --batch-size 16 --img-size 320 --name yolov5_lites
下面的训练曲线是正常的：
![image](https://github.com/ppogg/YOLOv5-Lite/assets/31054848/bea21ac7-998e-4a8f-b398-27cd2b52889c)

<html>
<body>
<div class="overview-key" style="--tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(57 126 237 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); box-sizing: inherit; width: 128px; flex-shrink: 0; color: rgb(170, 170, 170); font-family: &quot;Source Sans Pro&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.1px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System Hardware</div><div class="overview-value" style="--tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(57 126 237 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); box-sizing: inherit; color: rgb(54, 58, 61); font-family: &quot;Source Sans Pro&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.1px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

CPU count | 6
-- | --
GPU count | 1
GPU type | GeForce RTX 2060

</div>
</body>
</html>
