### ISSUE TITLE
YOLOv5-Lite do not recognize torch

### ISSUE THREAD

**Issue by EduardoRonchi** [ppogg/YOLOv5-Lite#108]
Hello, first of all, great project! Thanks for sharing you work with the community!

I am running a Raspberry Pi 4b 8Gb and I can't run yolov5-lite. I have python 3.7.3 and torch 1.8.0a0+56b43f4 installed. I can run regular YoloV5 normally, but when I try to run detect.py from YoloV5-lite I receive the following error:

![image](https://user-images.githubusercontent.com/54606018/151806110-436442eb-d734-4a14-8a8e-65a498b0c396.png)

When I check the torch version it says 1.8.0:
![image](https://user-images.githubusercontent.com/54606018/151806440-01ef5263-089e-465c-bfc3-1b2b9c2d7cb5.png)

Any ideas of what is wrong? 
Thanks in advance.

Ful logs:
```
(pytorch_venv) pi@raspberrypi:~/pytorch_env/YOLOv5-Lite $ python3 detect.py --source 0
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.45, device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='weights/v5lite-s.pt')
requirements: torch>=1.8.0 not found and is required by YOLOv5, attempting auto-update...
  Could not find a version that satisfies the requirement torch>=1.8.0 (from versions: )
No matching distribution found for torch>=1.8.0
Traceback (most recent call last):
  File "/home/pi/pytorch_env/YOLOv5-Lite/utils/general.py", line 110, in check_requirements
    pkg.require(r)
  File "/home/pi/pytorch_env/pytorch_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pi/pytorch_env/pytorch_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (torch 1.8.0a0+56b43f4 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('torch>=1.8.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 171, in <module>
    check_requirements(exclude=('pycocotools', 'thop'))
  File "/home/pi/pytorch_env/YOLOv5-Lite/utils/general.py", line 114, in check_requirements
    print(subprocess.check_output(f"pip install '{e.req}'", shell=True).decode())
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'pip install 'torch>=1.8.0'' returned non-zero exit status 1.
(pytorch_venv) pi@raspberrypi:~/pytorch_env/YOLOv5-Lite $ python3 
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.8.0a0+56b43f4
>>> 
```

**Comment by EduardoRonchi** [comment]
I am trying to find the wheels for rpi buster arm7l, but wthout any luck. Tried to build from source, but faced some error which I am trying to resolve now. Thanks for the fast answer, when I figure out how to install a newer version I will update this post. Thanks.

**Comment by EduardoRonchi** [comment]
Hey, managed to install torch 1.9.0 and it is recognized now, but another error is thrown:

![image](https://user-images.githubusercontent.com/54606018/152242122-c8302392-a5e4-408a-8c70-e3770bb161c9.png)

```
pi@raspberrypi:~/YOLOv5-Lite $ python3 detect.py --source 0
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.45, device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='weights/v5lite-s.pt')
YOLOv5  v1.3-179-g845749f torch 1.9.0a0+gitd69c22d CPU

Fusing layers... 
/home/pi/.local/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /home/pi/pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 230 layers, 1640661 parameters, 0 gradients, 3.9 GFLOPS
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 51, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "/home/pi/YOLOv5-Lite/utils/datasets.py", line 279, in __init__
    if 'youtube.com/' in url or 'youtu.be/' in url:  # if source is YouTube video
TypeError: argument of type 'int' is not iterable
```
