### ISSUE TITLE
rep_convert.py

### ISSUE THREAD

**Issue by diangu001** [ppogg/YOLOv5-Lite#139]
rep_convert.py运行这个文件后，会得到一个新的权重，将新的权重放在test和detect中运行报错。
AttributeError: 'Model' object has no attribute 'get'

**Comment by ppogg** [comment]
> rep_convert.py运行这个文件后，会得到一个新的权重，将新的权重放在test和detect中运行报错。 AttributeError: 'Model' object has no attribute 'get'

今早试了一下，原仓库正常没报错，你是用的v5第六版加载的是吗？

**Comment by diangu001** [comment]
我刚刚又重新下载了下YOLOv5-Lite的Code ，然后运行rep_convert，转化v5lite-g.pt，然后运行detect.py，最后还是报错。
AttributeError: 'Model' object has no attribute 'get'。顺便多嘴问一句，大佬的v5-lite模型训练的时候加载了预训练模型吗？加载的是yolov5s吗？

**Comment by diangu001** [comment]
rep_convert.py运行不会报错，但是得到的新模型不能用于推理。

**Comment by ChungTak** [comment]
@ppogg 试了最新代码，我也遇到这个问题，没有改过代码。我的重现步骤是
1.下载最新代码,安装依赖
git clone https://github.com/ppogg/YOLOv5-Lite.git
2.下载官方预训练模型v5lite-g.pt 放在YOLOv5-Lite/weights目录下
3.修改rep_convert.py    load = r'weights/v5lite-g.pt'
```
if __name__ == '__main__':
    load = r'weights/v5lite-g.pt'
    save = r'weights/repv5lite-g.pt'
    test_size = 640

```
4.执行python3 scripts/rep_convert.py
4.执行预测
```
python3 detect.py --weights weights/repv5lite-g.pt --source python_demo/openvino/bike.jpg 

```
5.出现异常
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.45, device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='python_demo/openvino/bike.jpg', update=False, view_img=False, weights=['weights/repv5lite-g.pt'])
YOLOv5 🚀 52afafd torch 1.10.2+cu102 CUDA:0 (GeForce GTX 1070, 8117.5625MB)

Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 34, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/media/vlinker/datavol/workspace/opensource/YOLOv5-Lite/models/experimental.py", line 121, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/vlinker/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'get'
```

**Comment by godxiang** [comment]
我也遇到这个问题，请问解决了吗

**Comment by 619732457** [comment]
> 我也遇到这个问题，请问解决了吗

#116 我根据这个回答修改了，可以运行。但有个问题，rep_convert之后的模型大小变大了，而且推理速度没有变快，我想请问下这个问题可能出现在哪里

**Comment by 1579093407** [comment]
> 
我遇到了同样的问题，请问您解决了吗
