### ISSUE TITLE
使用自定义数据集训练YOLOv5-Lite时报错

### ISSUE THREAD

**Issue by Aqua928** [ppogg/YOLOv5-Lite#173]
使用自己数据集训练YOLOv5-Lite过程中，生成metrics的时候报错如下，是什么原因导致的呢？查了下自定义的yaml中的文件路径和标注信息配置没有问题，其他的都没有改

报错如下：
```
Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
      0/99     5.23G    0.1221    0.0377   0.02721     0.187        23       640:   1%|█▏                                                                                                                | 1/99 [00:03<05:12,  3.19s/it]
Reducer buckets have been rebuilt in this iteration.
      0/99      1.8G    0.1013   0.03108    0.0247     0.157         3       640: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:34<00:00,  2.83it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0%|                                                                                                              | 0/12 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 355, in train
    results, maps, times = test.test(data_dict,
  File "/root/yolov5-lite/YOLOv5-Lite/test.py", line 110, in test
    out, train_out = model(img, augment=augment)  # inference and training outputs
ValueError: too many values to unpack (expected 2)
Killing subprocess 39567
Killing subprocess 39568
Killing subprocess 39569
Killing subprocess 39570
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/bin/python', '-u', 'train.py', '--local_rank=3', '--data', 'data/mask_data_neg.yaml', '--cfg', 'models/v5Lite-g.yaml', '--weights', 'pretrained/v5lite-g.pt', '--batch-size', '64', '--epochs', '100', '--device', '0,1,2,3', '--workers', '32']' returned non-zero exit status 1.`
```

**Comment by Aqua928** [comment]
命令行参数：
```
python train.py --data data/mask_data_neg.yaml --cfg models/v5Lite-g.yaml --weights pretrained/v5lite-g.pt --batch-size 32 --epochs 100
```
yaml文件配置：
```
# Custom data for safety helmet


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /root/yolov5-lite/YOLOv5-Lite/data/maskdataset_neg/images/train
val: /root/yolov5-lite/YOLOv5-Lite/data/maskdataset_neg/images/val2

# number of classes
nc: 2

# class names
names: ['face', 'mask']
```
cfg文件

**Comment by ppogg** [comment]
已解决，请重新尝试！

**Comment by Aqua928** [comment]
感谢！已解决

**Comment by PDYDBZ** [comment]
?我也出了Traceback (most recent call last):
  File "D:/Pycharm/YOLOv5-Lite-master/train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:/Pycharm/YOLOv5-Lite-master/train.py", line 355, in train
    results, maps, times = test.test(data_dict,
  File "D:\Pycharm\YOLOv5-Lite-master\test.py", line 110, in test
    out, train_out = model(img, augment=augment)  # inference and training outputs
ValueError: too many values to unpack (expected 2)
看不懂你们是怎么解决的

**Comment by PDYDBZ** [comment]
重试也没用
