### ISSUE TITLE
多GPU训练,torch.cuda.device_count()一直为1

### ISSUE THREAD

**Issue by cqray1990** [ppogg/YOLOv5-Lite#195]
命令：python3.8 -m torch.distributed.launch --nproc_per_node=2 --master_port=9999 train.py
Traceback (most recent call last):
  File "train.py", line 526, in <module>
    assert torch.cuda.device_count() > opt.local_rank
AssertionError
⚠️ WARNING: code is out of date by 38 commits. Use 'git pull' to update or 'git clone https://github.com/ppogg/YOLOv5-Lite' to download latest.
Resuming training from ./runs/train/exp5/weights/last.pt
YOLOv5 🚀 v1.4-7-g5d95d06 torch 1.10.2+cu102 CUDA:0 (GeForce RTX 2080 Ti, 11011.0625MB)

=== 0
Added key: store_based_barrier_key:1 to store for rank: 0
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1391 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 1392) of binary: /.conda/envs/yoloptdet/bin/python3.8
Traceback (most recent call last):
  File "/.conda/envs/yoloptdet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.conda/envs/yoloptdet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/.conda/envs/yoloptdet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-09_11:32:17
  host      : -MS-7B22
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1392)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
代码 没改动，以前能跑，多GPU突然就跑不了了

**Comment by ppogg** [comment]
版本的问题，可能是你某个库升级导致的情况
