### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by danyow-cheung** [ppogg/YOLOv5-Lite#214]
in linux and windows,both are occured error
```(pure_yolo) D:\er_code\yolov5-lite>python detect.py --source 0
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.45, device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='weights/v5lite-s.pt')
YOLOv5  v1.4-51-gca7ed7c torch 1.13.0+cpu CPU

Fusing layers...
Model Summary: 230 layers, 1640661 parameters, 0 gradients
1/1: 0... Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 51, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "D:\er_code\yolov5-lite\utils\datasets.py", line 279, in __init__
    if 'youtube.com/' in url or 'youtu.be/' in url:  # if source is YouTube video
TypeError: argument of type 'int' is not iterable
```
![捕获](https://user-images.githubusercontent.com/76671016/205262257-10a3bd6a-f040-46df-9f8a-e88894af2e05.JPG)

another question,is that possible for me to load the model by hub or something else?

**Comment by RonanSee** [comment]
having the same issue currently
