### ISSUE TITLE
运行自己的数据集，出现如下错误

### ISSUE THREAD

**Issue by g101400** [ppogg/YOLOv5-Lite#221]
运行自己的数据集，出现如下错误
Traceback (most recent call last):
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\train.py", line 547, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\train.py", line 193, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\utils\datasets.py", line 63, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\utils\datasets.py", line 411, in __init__
    bi = np.floor(np.arange(n) / batch_size).astype(np.int)  # batch index
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by yugezailushang** [comment]
我也是，请问你怎么解决的

**Comment by NakanoSanku** [comment]
使用`pip install "numpy<1.24.0"`可以解决，也可以通过修改源码中的np.int 为int

**Comment by flyskywhy** [comment]
Fix it in https://github.com/flyskywhy/YOLOv5-Lite/commit/4349e59f9bf3840522156c3f580a4b9b9c9e1441
