### ISSUE TITLE
训练时候错误提示

### ISSUE THREAD

**Issue by g101400** [ppogg/YOLOv5-Lite#222]
Scaled weight_decay = 0.0005
Optimizer groups: 82 .bias, 82 conv.weight, 79 other
Traceback (most recent call last):
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\train.py", line 547, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\train.py", line 193, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\utils\datasets.py", line 63, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "D:\myworkspace\yolov5\YOLOv5-Lite-master\utils\datasets.py", line 385, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str

**Comment by kirktt** [comment]
Maybe it’s the Cache under the dataset path, please try to delete the two files dataset/train/labels.cache and dataset/val/labels.cache
