### ISSUE TITLE
shufflenetv2预训练的模型的问题 

### ISSUE THREAD

**Issue by baibsB** [ppogg/YOLOv5-Lite#246]
Traceback (most recent call last):
  File "D:\pycharm\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Python\Projects\MachineLearn\FibreDetect\yolov5-master-Shufflenetv2\train.py", line 632, in <module>
    main(opt)
  File "D:\Python\Projects\MachineLearn\FibreDetect\yolov5-master-Shufflenetv2\train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\Python\Projects\MachineLearn\FibreDetect\yolov5-master-Shufflenetv2\train.py", line 124, in train
    csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
KeyError: 'model'

请问加载预训练模型时出现这个错误是为什么呢？

**Comment by ppogg** [comment]
这是一种常见的错误，出现在使用预训练模型加载时报错，建议打印模型的所有key进行比对~
