### ISSUE TITLE
Problem converting yolov5-lite to tflite

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ppogg/YOLOv5-Lite#28]
When launching according to ultralytics this line:

```
python models/tf.py --weights weights/yolov5-lite.pt --cfg models/yolov5-lite.yaml --tfl-int8 --source data/images/ --ncalib 100
```
I get the following error:

```
2021-09-22 07:53:50.613057: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-22 07:53:50.613133: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Namespace(agnostic_nms=False, batch_size=1, cfg='models/yolov5-lite.yaml', dynamic_batch_size=False, img_size=[320, 320], iou_thres=0.5, ncalib=100, score_thres=0.4, source='data/images/', tf_nms=False, tf_raw_resize=False, tfl_int8=True, topk_all=100, topk_per_class=100, weights='weights/yolov5-lite.pt')
Traceback (most recent call last):
  File "models/tf.py", line 458, in <module>
    model = attempt_load(opt.weights, map_location=torch.device('cpu'), inplace=True, fuse=False)
  File "./models/experimental.py", line 94, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'conv_bn_relu_maxpool' on <module 'models.common' from './models/common.py'>
```
Any idea in how to solve this?

**Comment by JNaranjo-Alcazar** [comment]
I solved this issue copying the tf.py from ultralytics to this repo folder.
However, I get the following error now:

```
Starting TensorFlow saved_model export with TensorFlow 2.4.1...
TensorFlow saved_model export failure: name 'tf_conv_bn_relu_maxpool' is not defined
Traceback (most recent call last):
  File "models/tf.py", line 466, in <module>
    tf_model = tf_Model(opt.cfg, model=model, nc=nc)
  File "models/tf.py", line 346, in __init__
    self.model, self.savelist = parse_model(deepcopy(self.yaml), ch=[ch], model=model)  # model, savelist, ch_out
  File "models/tf.py", line 316, in parse_model
    tf_m = eval('tf_' + m_str.replace('nn.', ''))
  File "<string>", line 1, in <module>
**NameError: name 'tf_conv_bn_relu_maxpool' is not defined**

Starting TensorFlow GraphDef export with TensorFlow 2.4.1...
TensorFlow GraphDef export failure: name 'keras_model' is not defined
Traceback (most recent call last):
  File "models/tf.py", line 491, in <module>
    tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
NameError: name 'keras_model' is not defined

Starting TFLite export with TensorFlow 2.4.1...

TFLite export failure: name 'keras_model' is not defined
Traceback (most recent call last):
  File "models/tf.py", line 521, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
NameError: name 'keras_model' is not defined
```

**Comment by JNaranjo-Alcazar** [comment]
So, I guess is not possible? To convert this model to tflite?

**Comment by taloot** [comment]
did you try openviono approach?

**Comment by ppogg** [comment]
[https://github.com/PINTO0309/openvino2tensorflow/issues/82](https://github.com/PINTO0309/openvino2tensorflow/issues/82)
It include all the tflife model, like fp16, fp32, int8
