### ISSUE TITLE
Add PicoDet

### ISSUE THREAD

**Issue by ppogg** [ppogg/YOLOv5-Lite#85]
此处添加PicoDet的复现代码，添加PicoDet-s.yaml, PicoDet-m.yaml, PicoDet-l.yaml, PicoDet-x.yaml，若复现出现问题或关于PicoDet的复现有新的想法，欢迎在此issue下方讨论~

**Comment by Pillar1989** [comment]
PicoDet-S  有没有模型？

**Comment by ppogg** [comment]
> PicoDet-S 有没有模型？

目前没有预训练模型，本人也没有显卡可用，如果您有兴趣尝试模型训练，欢迎pr

**Comment by Pillar1989** [comment]
@ppogg  我有显卡，你想用什么数据集，用什么参数，我来训练

**Comment by Pillar1989** [comment]
```bash
(base) se@stu:~/YOLOv5-Lite$ python train.py --img 320 --batch 6000 --epochs 200 --data coco.yaml --cfg PicoDet-s.yaml
github: up to date with https://github.com/ppogg/YOLOv5-Lite/ ✅
YOLOv5 🚀 v1.3-105-gdbfd5c1 torch 1.10.1 CUDA:0 (NVIDIA A100-PCIE-40GB, 40536.1875MB)

Namespace(weights='weights/v5lite-s.pt', cfg='./models/hub/PicoDet-s.yaml', data='./data/coco.yaml', hyp='data/hyp.scratch.yaml', epochs=200, batch_size=6000, img_size=[320, 320], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, image_weights=False, device='0', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, workers=8, project='runs/train', entity=None, name='exp', exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias='latest', world_size=1, global_rank=-1, save_dir='runs/train/exp4', total_batch_size=6000)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.001, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.2, mixup=0.0
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id 2p0e9lqc.
2022-01-13 06:01:48.163965: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/se/anaconda3/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-13 06:01:48.164004: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

                 from  n    params  module                                  arguments                     
  0                -1  1       928  models.common.CBH                       [3, 32, 3, 2]                 
  1                -1  1     23296  models.common.ES_Bottleneck             [32, 96, 2]                   
  2                -1  2     44160  models.common.ES_Bottleneck             [96, 96, 1]                   
  3                -1  1     93792  models.common.ES_Bottleneck             [96, 192, 2]                  
  4                -1  5    416640  models.common.ES_Bottleneck             [192, 192, 1]                 
  5                -1  1    362688  models.common.ES_Bottleneck             [192, 384, 2]                 
  6                -1  2    646656  models.common.ES_Bottleneck             [384, 384, 1]                 
  7                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
  8           [-1, 6]  1         0  models.common.Concat                    [1]                           
  9                -1  1     90528  models.common.BottleneckCSP             [576, 96, 1, False]           
 10                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 4]  1         0  models.common.Concat                    [1]                           
 13                -1  1     62880  models.common.BottleneckCSP             [288, 96, 1, False]           
 14                -1  1      9408  models.common.Conv                      [96, 96, 1, 1]                
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 2]  1         0  models.common.Concat                    [1]                           
 17                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 18                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 21                -1  1     12000  models.common.DWConvblock               [96, 96, 5, 2]                
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1     53664  models.common.BottleneckCSP             [192, 96, 1, False]           
 24           [-1, 7]  1         0  models.common.ADD                       [1]                           
 25                -1  1     17904  models.common.DWConvblock               [144, 96, 5, 2]               
 26  [17, 20, 23, 25]  1    131920  models.yolo.Detect                      [80, [[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]], [96, 96, 96, 96]]
Traceback (most recent call last):
  File "/home/se/YOLOv5-Lite/train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/se/YOLOv5-Lite/train.py", line 89, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 93, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/se/YOLOv5-Lite/models/yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "/home/se/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/se/YOLOv5-Lite/models/common.py", line 678, in forward
    return torch.add(x1, x2, self.a)
TypeError: add() takes 2 positional arguments but 3 were given

wandb: Waiting for W&B process to finish, PID 3276580... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/se/YOLOv5-Lite/wandb/offline-run-20220113_060147-2p0e9lqc
wandb: Find logs at: ./wandb/offline-run-20220113_060147-2p0e9lqc/logs/debug.log
wandb: 
```
看起来是不是有写代码没有提交呢？ @ppogg

**Comment by ppogg** [comment]
收到，麻烦另开一个issue通道，我标记为bug，今晚修补！

**Comment by Pillar1989** [comment]
https://github.com/ppogg/YOLOv5-Lite/issues/101 @ppogg  已开

**Comment by regainOWO** [comment]
PicoDet-s.yaml 相比PicoDet-m.yaml PicoDet-l.yaml PicoDet-x.yaml有些区别
https://github.com/ppogg/YOLOv5-Lite/blob/ca7ed7ca0bb578fe6e5eaa777e84f661ad457e49/models/hub/PicoDet-s.yaml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L45
s用的是Add，其他的则是用的concat，有什么区别吗？

**Comment by ppogg** [comment]
可参考picodet的论文，按照网络框架复现的
